### ISSUE TITLE
How to make access.log with lager? [JIRA: RIAK-1901]

### ISSUE THREAD

**Issue by maxlapshin** [basho/lager#144]
I try to make a separate access.log with lager and write there only messages with specific tag:

    lager:debug([{request,web},{duration,Time}],"~3..0B ~5.. B ~B ~s ~p", [Code,Time, Size, Path, SessionId]),

or 

    lager:info([{request,web},{duration,Time}],"~3..0B ~5.. B ~B ~s ~p", [Code,Time, Size, Path, SessionId]),

Is it possible to make a trace file and configure it so, that only log events with meta  {request,web} will get there?

**Comment by mrallen1** [comment]
The 3.0 branch supports multiple sinks with multiple configuration values directly.
