### ISSUE TITLE
Metadata not used as backend configuration? [JIRA: RIAK-1900]

### ISSUE THREAD

**Issue by tolbrino** [basho/lager#161]
I recall having seen a note that in 2.0.0 one would be able to pass any metadata into a handler's configuration, allowing the filtering of messages to be logged by the handler.

My use case is that I'd like to classify logs using {class, some_class} and direct the logs to separate files for each class, as well as having a catch_all handler for the rest of the logs.

I might have totally misunderstood the feature since I couldn't find any hint in the code.

**Comment by mrallen1** [comment]
The 3.0 release supports multiple sinks to multiple backends with multiple configurations.
