### ISSUE TITLE
Lager does not perform any group leader redirection from error_logger messages [JIRA: RIAK-1897]

### ISSUE THREAD

**Issue by josevalim** [basho/lager#223]
By default, Erlang keeps an `error_logger` handler running for the sole purpose of redirecting messages between nodes:

https://github.com/erlang/otp/blob/OTP-17.0/lib/kernel/src/error_logger.erl#L367-L370

You can use `gen_event:which_handlers(error_logger)` to see there is always an `error_logger` handler in there. All other erlang handlers by default ignore messages coming from other nodes as they assume a redirection will happen, for example:

https://github.com/erlang/otp/blob/OTP-17.0/lib/stdlib/src/error_logger_tty_h.erl#L54-L55

However, lager by default removes all error_logger handlers:

https://github.com/basho/lager/blob/2.0.3/src/lager_app.erl#L109-L110

And the default logger installed by lager does not do any redirection based on the node group leader:

https://github.com/basho/lager/blob/2.0.3/src/error_logger_lager_h.erl#L148

This basically means that, after lager is installed, there is no node redirection happening. The main downside of this behaviour is that when using remote shells, the log messages are no longer redirected. The same with executing processes on remote nodes, where you may expect at the least the crash to be reported in the caller.

However, lager may have good reasons to remove this behaviour, however I could not find a rationale anywhere. So is it a bug or a feature? :D

**Comment by mrallen1** [comment]
In 3.x we have group leader support. Still probably need to fix up the emulator messages though.

**Comment by mrallen1** [comment]
Closing this for now, please reopen if we missed something.
