### ISSUE TITLE
add hostname/IP to lager output [JIRA: RIAK-1896]

### ISSUE THREAD

**Issue by michellep-basho** [basho/lager#228]
<b>Requestor:</b> Bryan H (Basho CS)
<b>Drivers:</b> support efficiency - faster troubleshooting, facilitate trending/log mining

<b>Description:</b>
For every line of lager output from any of our products - format the text in this fashion - 2014-08-03 07:13:23.595 [error] [your.host.name] <0.26631.1037>@riak_kv_console:transfers:278 Transfers failed error:terminated

The change would be the addition of the your.host.name field. 
It would make it massively easier to plot issues across all the hosts in a cluster, looking on a host by host basis doesn't make sense in a product like riak, it would be far better if we could aggregate bad behavior across the entire cluster. 

Having the hostname or ip address embedded in every lager log message would make it massively easier to do - which would save time and money.

**Comment by mrallen1** [comment]
`perl -n -E'say "$ARGV[0] : $_"' /var/log/system.log `hostname``
