### ISSUE TITLE
Log to seperate file

### ISSUE THREAD

**Issue by expelledboy** [basho/lager#239]
We have an application that logs user interaction with an application which interfaces with a bank. Naturally this is all very sensitive, but for auditing purposes its required.

Currently we use our own logging component, which we can invoke as follows:
```
GlobalLogger = banking_application.
ok = glog:write(GlobalLogger,"User ~p has cancelled transaction ~p", [User, Trx]).
```
The atom maps to a glog configuration entry with its filename etc.

Is there anyway to do this using lager?

Some issues which would be resolved by addressing this question include #144 #230, as they essentially was to achieve the same thing.

**Comment by mrallen1** [comment]
Hi. The forthcoming 3.0 branch allows for multiple sinks which is exactly what you're asking for here.

**Comment by expelledboy** [comment]
+1
