### ISSUE TITLE
Inappropriate child_spec in lager_sup [JIRA: RIAK-1848]

### ISSUE THREAD

**Issue by fauxsoup** [basho/lager#271]
*This is not a runtime issue and will cause no issues unless someone creates a relup or appup file which attempts to suspend the lager gen_event process*.

Please see this line: https://github.com/basho/lager/blob/master/src/lager_sup.erl#L39

The Modules part of that child specification should be `dynamic` and not `[dynamic]`. This is because the release_handler process will always consider a list of atoms to be a list of modules the process is running. As such, when encountering this child specification, it will interpret it to mean that this process is only running a module named `dynamic`. The singular atom `dynamic` should be used when describing a process which uses modules specified at runtime.

**Comment by mrallen1** [comment]
Thanks for the report! We will fix this in a future release.

**Comment by mrallen1** [comment]
Fixed in 6a458a4

**Comment by mrallen1** [comment]
Fixed in 6a458a4

**Comment by mrallen1** [comment]
This should be resolved in 3.0 now on master. Closing.
