### ISSUE TITLE
Lager crash log path does not honor log_root [JIRA: RIAK-1882]

### ISSUE THREAD

**Issue by Vagabond** [basho/lager#274]

**Comment by mrallen1** [comment]
This is for the release version?  I think we could get a fix in place for this before all of the review-mergy-mergy stuff that's still not finished.

**Comment by Vagabond** [comment]
Yeah, I just ran into it, affects latest 2.x and probably upcoming 3.x

**Comment by mrallen1** [comment]
Just added some crash_log unit tests with log_root on 3.x and they all pass. :cake: Going to check on 2.x now.

**Comment by mrallen1** [comment]
OK, so these unit tests are not capturing the failure.  Can you be more specific about what's failing?

**Comment by mrallen1** [comment]
@Vagabond if you have a moment to update this ticket - I'd really like to get this resolved for you.  My test case is not capturing a failure, so if you can provide additional information it would be really helpful. Thanks.

**Comment by Vagabond** [comment]
Yeah, I'm kind of baffled, reading the code, why I had this not working. As far as your testcases and the code look, this should work. Might just have been misdiagnosis or a problem with lager getting reverted to an older version on my part.

**Comment by Vagabond** [comment]
I think we can close this.

**Comment by mrallen1** [comment]
OK. Thanks for the clarification. I'll get #277 rebased to master for a 3.next release soon.
