### ISSUE TITLE
Changelog [JIRA: RIAK-2131]

### ISSUE THREAD

**Issue by qrilka** [basho/lager#289]
It's not quite easy to get form the repo any information what has changed when version 3 of lager came up.
I have googled http://erlang.org/pipermail/erlang-questions/2015-June/084816.html of course but it's a good practice to have at least some basic Changelog file.

**Comment by mrallen1** [comment]
Thanks for the feedback. Historically we haven't kept a change log but I do see a need for one. We'll try to keep a simple changelog in the README file.
