### ISSUE TITLE
There is no log when an application stop. [JIRA: RIAK-2146]

### ISSUE THREAD

**Issue by mingchaoyan** [basho/lager#290]
I use 

    erl_call -s -a 'init stop' -name xxxx -c xxx 

I lager:info/1 in the xxx_app:stop/1, but there is no info log in log file. 

Maybe init stop will stop lager before xxx application.

So how to make lager to log start information and stop information?

Or lager not support to log in the function xxx_app:stop/1:

Or the way I use lager is wrong?

Or it is not the right way to stop a server use erl_call, what is your advice? 

Thank you very much!

**Comment by Vagabond** [comment]
There is a chance lager has been stopped at that point, yes. You might have better luck using the prep_stop callback, which will run before applications get shut down:

```
The application master calls Module:prep_stop/1, if such a function is defined, and then tells the top supervisor of the  application  to shutdown (see supervisor(3)). This means that the entire supervision tree, including included applications, is terminated in reversed start order. After the shutdown, the application master calls Module:stop/1
```

**Comment by mrallen1** [comment]
I'm going to close this issue since its been a few months since any new reply. Please reopen if needed. Thanks.
