### ISSUE TITLE
Large format string not truncated [JIRA: RIAK-2189]

### ISSUE THREAD

**Issue by jbothma** [basho/lager#293]
Is it a bug for large format strings not to get truncated, or is it improper usage of lager to give it large format strings?

My expectation is that the truncation is on the full log output (regardless of shortcuts in the implementation to avoid unnecessary processing)

```erlang
7> lager_trunc_io:format("~p~n", [iolist_to_binary([65||_<-lists:seq(1,100)])], 10, [{chomp,true}]).
["<<\"AAAAA...\">>"]

8> lager_trunc_io:format(iolist_to_binary([65||_<-lists:seq(1,100)]), [], 10, [{chomp,true}]).         
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
```

This is in vsn 2.1.1 and 3.0.1

**Comment by Vagabond** [comment]
We don't consider large format strings to be 'runaway behaviour', we are more concerned about format arguments that have an undefined size causing OOM conditions.

**Comment by jbothma** [comment]
ok - this hits when I know what I'm logging is a binary - I was under the impression that I could just drop it into the format argument, but sounds like the expectation is that the size of the format argument should be known, and anything of unknown size should be formatted in as an arg.

Thanks for the quick explanation!

**Comment by mrallen1** [comment]
I'm going to close this. Please reopen if you still need help with this. Thanks.
