### ISSUE TITLE
Does trace to file work properly? [JIRA: RIAK-2326]

### ISSUE THREAD

**Issue by malotte** [basho/lager#304]
When adding traces using lager:trace_file/3 it seems like the log_root is added twice.
I. e. when using log_root = "log/lager" the file ends up at log/lager/log/lager.
Furthermore, no trace output is written to the file as far as I can see.

Add trace:
(hoc33@venus)2> lager:trace_file("debug.log", [{module, nmea_2000_log}], debug). 
{ok,{{lager_file_backend,"log/lager/debug.log"},
     [{module,nmea_2000_log}],
     debug}}
(hoc33@venus)3> lager:status().                                                 Lager status:
File log/lager/debug.log (lager_event) at level none
File log/lager/http.log (lager_event) at level none
Console (lager_event) at level info
File error.log (lager_event) at level warning
File console.log (lager_event) at level info
Active Traces:
Tracing messages matching {all,[{module,'=',nmea_2000_log}]} (sink lager_event) at level debug to {lager_file_backend,
                                                                                                   "log/lager/debug.log"}
Tracing messages matching {all,[{module,'=',seaz_ws},
                                {function,'=',handle_http_request}]} (sink lager_event) at level debug to {lager_file_backend,
                                                                                                           "log/lager/http.log"}
Tracing Reductions:
{any,[{all,[{function,'=',handle_http_request},{module,'=',seaz_ws}]},
         {module,'=',nmea_2000_log}]}
Tracing Statistics:
  input: 0
 output: 0
 filter: 0
ok

Log:
hoc33@venus)4> lager:log(debug, [{module, nmea_2000_log}], "test").
ok
(hoc33@venus)5> lager:status().                                     
Lager status:
File log/lager/debug.log (lager_event) at level none
File log/lager/http.log (lager_event) at level none
Console (lager_event) at level info
File error.log (lager_event) at level warning
File console.log (lager_event) at level info
Active Traces:
Tracing messages matching {all,[{module,'=',nmea_2000_log}]} (sink lager_event) at level debug to {lager_file_backend,
                                                                                                   "log/lager/debug.log"}
Tracing messages matching {all,[{module,'=',seaz_ws},
                                {function,'=',handle_http_request}]} (sink lager_event) at level debug to {lager_file_backend,
                                                                                                           "log/lager/http.log"}
Tracing Reductions:
{any,[{all,[{function,'=',handle_http_request},{module,'=',seaz_ws}]},
      {module,'=',nmea_2000_log}]}
Tracing Statistics:
  input: 1
 output: 1
 filter: 0
ok

No output:
malotte@venus:/Users/Malotte/erlang/hoc33 [master]$ll log/lager/log/lager/
total 0
drwxr-xr-x  4 malotte  staff  136 Dec 14 16:09 .
drwxr-xr-x  4 malotte  staff  136 Dec 14 16:08 ..
-rw-r--r--  1 malotte  staff    0 Dec 14 16:08 debug.log
-rw-r--r--  1 malotte  staff    0 Dec 14 16:09 http.log

I have the same problem with traces added in the system configuration file:
	  {traces, [{{lager_file_backend, "http.log"},
		     [{module, seaz_ws}, 
		      {function, handle_http_request}],
		     debug}]}

Am I doing something wrong?
I am using lager 3.0.2.

Regards,
Malotte

**Comment by malotte** [comment]
I've done some tracing and it looks like lager, in the lager_util module, is comparing file names where one is expanded twice and the other one isn't .
Code:
is_loggable(Msg, {mask, Mask}, MyName) ->
    %% using syslog style comparison flags
    %S = lager_msg:severity_as_int(Msg),
    %?debugFmt("comparing masks ~.2B and ~.2B -> ~p~n", [S, Mask, S band Mask]),
    (lager_msg:severity_as_int(Msg) band Mask) /= 0 orelse
	lists:member(MyName, lager_msg:destinations(Msg));

Trace:
is_loggable,myname,{lager_file_backend,"log/lager/log/lager/debug.log"}}
{is_loggable,destinations,[{lager_file_backend,"log/lager/debug.log"}]}

Regards,
Malotte

**Comment by mrallen1** [comment]
Thanks for looking into this. We are planning to look into recent lager PRs and issues on Thursday afternoon US time.

**Comment by malotte** [comment]
Hi again,
I think the reason I get this problem is that I used a relative path as log_root.
If you use an absolute path the second of the two calls to lager_util:expand_path/1 makes no difference since filename:join(AbsPath1, AbsPath2) returns AbsPath2 but if you use a relative path it gets added twice since filename:join(RelPath1, RelPath2) returns RelPath1/RelPath2.
So if you don't want to fix this you should state clearly that log_root must be absolute.

Regards,
Malotte

**Comment by mrallen1** [comment]
Thanks for the update. I'm not sure we have ever settled definitively on a absolute/relative value for `log_root` but maybe we ought to.

**Comment by mrallen1** [comment]
Just coming back to this now - I think we should try to convert the relative path to an absolute path in the `lager_util:expand_path` call.

**Comment by mrallen1** [comment]
OK, I pushed a potential fix in #317 - if you have a moment, would you please try the `gh304` branch and let me know if it fixes your problem. I made a unit test that fails without the patch and passes with it, so I think I am fixing the right problem.

Thanks.

**Comment by malotte** [comment]
Seems to work :-)

Thanks.

**Comment by mrallen1** [comment]
#317 has been tagged as a release. Closing. Thanks for your help!
