### ISSUE TITLE
[Question] Ho to use lager with rebar3 in eunit? [JIRA: RIAK-2344]

### ISSUE THREAD

**Issue by CyborTronik** [basho/lager#310]
I just started to user rebar3 and I have next config in `rebar.config` (I'm not sure if it's right, but seems to be) :
```
{erl_opts, [debug_info, parse_transform, lager_transform]}.
{deps, [
  {lager, ".*", {
    git, "git://github.com/basho/lager.git", "master"}
  }
]}.

{relx, [{release, {'nlp_rel', "0.1.0"},
  ['nlp_rel',
    lager,
    sasl]},

  {sys_config, "./config/sys.config"},
  {vm_args, "./config/vm.args"},

  {dev_mode, true},
  {include_erts, false},

  {extended_start_script, true}]
}.

{lager, [
  {log_root, "/var/log/nlp_rel"},
  {handlers, [
    {lager_console_backend, info},
    {lager_file_backend, [{file, "error.log"}, {level, error}]},
    {lager_file_backend, [{file, "console.log"}, {level, info}]}
  ]}
]}.

{profiles,
  [
    {prod, [{
      relx,
      [{dev_mode, false}, {include_erts, true}]
    }]},
    {test, [{
      erl_opts, [debug_info]
    }]}
  ]
}.
```

So how is possible to use lager during: rebar3 eunit?

Many thanks

**Comment by mrallen1** [comment]
I honestly have no idea. @ferd or @tsloughter could maybe answer this question better.

**Comment by ferd** [comment]
Well first of all the lager app config does not go in rebar.config. Currently we have no way of loading app config files before test runs automatically (tracked at https://github.com/rebar/rebar3/issues/885 for common test, unrequested for eunit so far).

This means for the time being you may want to have your test generator manually set up lager for your test run.

Now it's hard to help more than this because I don't really know what you expect to see as an output and how what I say could be of more help.

**Comment by tsloughter** [comment]
I assume you aren't getting lager output like you'd expect? First, as fred mentioned, `rebar.config` is not the proper place to configure `lager` runtime.

Then when your eunit tests are setup you need to start lager and read in any config values you want. An example from our tests at work:

```erlang
<our app name>_utils:set_config("./_build/test/extras/test/etc/app.config"),
lager:start(),
lager:set_loglevel(lager_console_backend, info),
```
This will populate the app env with what is in `test/etc/app.config` and start lager.

**Comment by CyborTronik** [comment]
It's a bit sad.
The idea behind is that I have no app yet, just started to implement one function and would be nice to have ability to trace/log details.

**Comment by Vagabond** [comment]
You can just set up an eunit fixture and start lager in setup() and stop it in teardown()

**Comment by mrallen1** [comment]
I'm going to close this for now. Reopen if you need further help.

**Comment by sstrigler** [comment]
Just because I accidentally stumbled upon this, it must be

{erl_opts, [debug_info, {parse_transform, lager_transform}]}.

Not sure if it helps with eunit though.

**Comment by drozzy** [comment]
This correct answer is given above by @sstrigler.
