### ISSUE TITLE
renable travis Build status on project pages shows last run was a few years ago.  [JIRA: RIAK-2404]

### ISSUE THREAD

**Issue by linearregression** [basho/lager#320]
possible to turn travisci on again to make the test run status more transparent?

**Comment by mrallen1** [comment]
We can look into it. @Vagabond - if you have a moment - what was the history around turning off Travis in the first place?

**Comment by Vagabond** [comment]
It was unreliable, slow and we had switched to buildbot/bors.

Hopefully the Erlang builder isn't on the same host as the Java builder anymore, it should be fine.

**Comment by linearregression** [comment]
I bet travisci may be a lot better now. MachineZone use travis for their mzbench testing that invokes a cluster setup for multi node testing. It may be nice to reenable it or at least make unit test for each run visible. A local run if tests already shows multiple failures.

**Comment by michalwski** [comment]
:+1: for this. We've been using travis for esl/MongooseIM for long time already and recently I observed significant performance/stability improvement, especially when you use the container-based infrastructure. New repos added to travis have this by default but old can enable this infrastructure by specifying `sudo: false` in the .travis.yml file, from what I know.

**Comment by Vagabond** [comment]
No objection to re-enabling it.

**Comment by JeetKunDoug** [comment]
I've turned it back on for PRs (other options include all pushes, which seemed not useful). We'll probably need some work to get it up and running again properly, so I wouldn't assume that the first couple will pass.

**Comment by mrallen1** [comment]
Just merged #340 to update the OTP releases. Going to close this now - please reopen if something seems amiss.

**Comment by mrallen1** [comment]
Ah, forgot to re-enable the TravisCI web hook on the repo. Is that something you can do @JeetKunDoug?

**Comment by JeetKunDoug** [comment]
Should be on now. Let me know if it doesn't work. Closing this until I hear otherwise.
