### ISSUE TITLE
R15 comat [JIRA: RIAK-2436]

### ISSUE THREAD

**Issue by tonyrog** [basho/lager#329]
Hi!
Tried run lager on raspberry pi today. but got a problem with error_logger_lager_h.erl using application:get_env/3 that do not exist on R15. R15 is the default Erlang on raspberry pi so
it would be VERY nice to avoid compiling Erlang for raspberry pi bacuse of this little issue. Here is git diff for the fix. But please free to fix in anyway you like. Thanks.

diff --git a/src/error_logger_lager_h.erl b/src/error_logger_lager_h.erl
index 9a42e2a..0079515 100644
--- a/src/error_logger_lager_h.erl
+++ b/src/error_logger_lager_h.erl
@@ -73,7 +73,7 @@ set_high_water(N) ->
 -spec init(any()) -> {ok, #state{}}.
 init([HighWaterMark, GlStrategy]) ->
     Shaper = #lager_shaper{hwm=HighWaterMark},
-    Raw = application:get_env(lager, error_logger_format_raw, false),
+    Raw = lager_app:get_env(lager, error_logger_format_raw, false),
     Sink = configured_sink(),
     {ok, #state{sink=Sink, shaper=Shaper, groupleader_strategy=GlStrategy, raw=
 
@@ -104,7 +104,7 @@ terminate(_Reason, _State) ->
 
 
 code_change(_OldVsn, {state, Shaper, GLStrategy}, _Extra) ->
-    Raw = application:get_env(lager, error_logger_format_raw, false),
+    Raw = lager_app:get_env(lager, error_logger_format_raw, false),
     {ok, #state{
         sink=configured_sink(), 
         shaper=Shaper, 
@@ -112,7 +112,7 @@ code_change(_OldVsn, {state, Shaper, GLStrategy}, _Extra) ->
         raw=Raw
         }};
 code_change(_OldVsn, {state, Sink, Shaper, GLS}, _Extra) ->
-    Raw = application:get_env(lager, error_logger_format_raw, false),
+    Raw = lager_app:get_env(lager, error_logger_format_raw, false),
     {ok, #state{sink=Sink, shaper=Shaper, groupleader_strategy=GLS, raw=Raw}};
 code_change(_OldVsn, State, _Extra) ->
     {ok, State}.
@@ -120,7 +120,7 @@ code_change(_OldVsn, State, _Extra) ->
 %% internal functions
 
 configured_sink() ->
-    case proplists:get_value(?ERROR_LOGGER_SINK, application:get_env(lager, ext
+    case proplists:get_value(?ERROR_LOGGER_SINK, lager_app:get_env(lager, extra
         undefined -> ?DEFAULT_SINK;
         _ -> ?ERROR_LOGGER_SINK
     end.
diff --git a/src/lager_app.erl b/src/lager_app.erl
index ebbf330..25babeb 100644
--- a/src/lager_app.erl
+++ b/src/lager_app.erl
@@ -29,7 +29,7 @@
          start/2,
          start_handler/3,
          stop/1]).
-
+-export([get_env/3]).
 -define(FILENAMES, '__lager_file_backend_filenames').
 -define(THROTTLE, lager_backend_throttle).
 -define(DEFAULT_HANDLER_CONF,

**Comment by Vagabond** [comment]
This is also being tracked over in #325
