### ISSUE TITLE
error_logger_lager_h:format_offender/1 looks for wrong key for offender name? [JIRA: RIAK-2471]

### ISSUE THREAD

**Issue by kennethlakin** [basho/lager#332]
For ages, I've been getting Lager crash reports of the form "Supervisor $SUP had child undefined started with ...", regardless of whether or not the crashing child was a registered process. So, I did some digging.

At https://github.com/basho/lager/blob/master/src/error_logger_lager_h.erl#L298 , we see that the offender's reported Name is being sourced from the ``'name'`` key in the ``Off`` proplist. However, inspection of the contents of the proplist reveals that there is no ``'name'`` key, but there *is* an ``'id'`` key that contains what appears to the be child ID that was passed to the supervisor for the crashing process. When I make the obvious change the crash message changes to "Supervisor $SUP had child $CHILD_ID started with ...", which looks more reasonable to me.

Issue #14  looks vaguely related, though 6fdbe250718c510e53b5824a37dfeece330c94f0 reveals that the code in question *never* got the "name" from the offender's ``id`` key... Is this a long-standing typo and the intention was for format_offender to get the child's ID from ``id``, or is there something I'm missing here?

**Comment by mrallen1** [comment]
Thanks for the report and thank you also for the code archeology. I can't speak to the history behind the changes, but I agree it would be nice to use the `id` if its available and has a value.  I think the way to do that would be to handle the case where name is `undefined` in a new function and return a different string more in line with your suggestion if `id` is populated.

**Comment by kennethlakin** [comment]
Does PR #333  address this issue to your satisfaction? It seemed natural to me to leave the string as-is (because what it says makes a lot of sense, given the context), but just use ``id`` as the source of the child name if ``name`` is missing. If both are missing, we fall back to ``undefined``.

I ran the test suite before and after making the change. The same nine tests failed each time.

If you like, I can do more spelunking to determine where the ``name`` key gets set (if it *ever* does) to make sure that just using ``id`` (rather than making a more substantial change) is acceptable in this case.

**Comment by macintux** [comment]
Digging through the history of the `supervisor` module it's clear that `name` was changed to `id` for the output of `extract_child/1` with this commit:

```
commit 1d4379e307cd7256e019e962b0ece6a1badcffb9
Author: Siri Hansen <siri@erlang.org>
Date:   Mon Jun 30 11:27:46 2014 +0200
```

Going to create a tweaked version of the PR that tries `id` first since that's the modern version of `name`. Thanks so much for investigating this and supplying a PR.

**Comment by kennethlakin** [comment]
> Digging through the [OTP] history...

Ooh! That's good spelunking.

In regards to PR #334 , won't that code as written try ``name`` first, typically pass ``undefined`` as the default to the ``get_value`` call, and then try ``id``? I don't know if the performance matters there, but if it does, shouldn't it be written as a ``case`` statement rather than a nested call?

**Comment by macintux** [comment]
I considered that and cursed the lack of laziness in the language which would have allowed me to be lazy in my coding…then went lazy anyway.

I’ll rewrite it as an orelse.

-John

**Comment by macintux** [comment]
Well, that was a stupid idea. `orelse` won't cut it.

You have no idea how much I hate `case` statements. Hrm.

**Comment by macintux** [comment]
`case` it is, under protest.

**Comment by kennethlakin** [comment]
You're right, I *don't* know how much you hate ``case`` statements. It's kinda off-topic, but I'd be interested in hearing your grievances if you're interested in telling the story.

**Comment by macintux** [comment]
I've just been brainwashed by @gar1t (http://www.gar1t.com/blog/solving-embarrassingly-obvious-problems-in-erlang.html).

I also intensely dislike the pattern I occasionally run into where a binding is redefined in each branch of a case statement, while we're on the topic.

**Comment by kennethlakin** [comment]
Ah, yeah I read that post. Because of it I do try to prefer function pattern matching to case statements whenever it "seems" reasonable to do so.

Is that binding redefinition you're talking about something like
```erlang
case Term of
    Bar when is_integer(Bar) -> int;
    Baz when is_list(Baz) -> list
end.
```
Or is it more like renaming a binding from an enclosing scope to something different in the code in each case statement?

**Comment by macintux** [comment]
This is what I'm describing. If there are any children in the room, make sure they avert their eyes.

```erlang
case Val of
    foo ->
        NewVal = fizz;
    bar ->
        NewVal = buzz
end
```

**Comment by kennethlakin** [comment]
Ah! My opinion on case's -er- scoping rules changes on a regular basis. I'll tactfully neglect to mention how the PRs associated with this bug could be rewritten to take advantage of this (mis?)feature.
