### ISSUE TITLE
hex.pm releases ? [JIRA: RIAK-2502]

### ISSUE THREAD

**Issue by jonathanperret** [basho/lager#349]
https://hex.pm/packages/lager contains packages for `lager` releases `2.1.1`, `3.0.1` and `3.0.2` but nothing after that. Was there a change in `lager`'s publishing policy?

**Comment by mrallen1** [comment]
AFAIK, no one at basho has ever published lager to into hex.pm - @Licenser did you push lager into hex? I know you submitted some other packages.

**Comment by jonathanperret** [comment]
I just counted 148 packages in hex.pm that declare a direct dependency on `lager`. May I suggest it would be helpful for `lager` users to have up-to-date releases on hex.pm?

My own case is that I published https://hex.pm/packages/logger_lager_backend that should depend on `lager` `3.2.0` because of the #326 fix, but I can't declare it because `3.2.0` is not on hex.pm. Is there maybe anything I can do to help?

**Comment by Vagabond** [comment]
We should designate someone to wrangle hex as part of releases. I've no idea how to do it (nor who has published lager to hex before).

**Comment by Licenser** [comment]
wasn't me, sorry for the late response.

**Comment by jaseemabid** [comment]
Can someone look into this? Maintainers listed on hex are Andrew Thompson and Jared Morrow. I dont mind updating lager versions on hex.pm, but I dont have the permissions.

**Comment by mrallen1** [comment]
And neither do they :(

Is there a document somewhere that describes how to put stuff on hex?

**Comment by jaseemabid** [comment]
https://hex.pm/docs/rebar3_publish

**Comment by mrallen1** [comment]
Cool thanks!

**Comment by tsloughter** [comment]
I published it. And i've updated to 3.2.0 today.

**Comment by mrallen1** [comment]
Thanks Tristan.

**Comment by jonathanperret** [comment]
Thanks a lot!

**Comment by mrallen1** [comment]
@tsloughter It looks like you're "the owner" of lager on hex. Can I also publish new releases to hex or is there some kind of handoff that needs to take place?
