### ISSUE TITLE
Could log level be configurable? [JIRA: RIAK-2517]

### ISSUE THREAD

**Issue by gy8409** [basho/lager#350]
I would like to log data access trace. It's very common for internet application which record when request come in and response goes out. I didn't find "access" in predefined log levels. Could level be configurable? If not, what's the replacement solution?

**Comment by gy8409** [comment]
I got it. I could use traces to create filter to do it like the way in issue https://github.com/basho/lager/issues/207

**Comment by mrallen1** [comment]
Glad you have a solution. Please open another ticket if you have any other questions/problems.
