### ISSUE TITLE
README.md usage example is too old ,some function is not exits  [JIRA: RIAK-2544]

### ISSUE THREAD

**Issue by stevensu1977** [basho/lager#353]
lager:error("Some message").
** exception error: undefined function lager:error/1

I think README.md is old , some function is not exits.

**Comment by mrallen1** [comment]
You have to use the parse transform to use that style of function call for lager.  The parse transform turns `lager:error` into the right thing.

**Comment by stevensu1977** [comment]
sorry I make mistake,  use -compile([{parse_transform, lager_transform}]).
  it's work !
