### ISSUE TITLE
Please release 3.2.1 :) [JIRA: RIAK-2592]

### ISSUE THREAD

**Issue by mremond** [basho/lager#362]
Hi,

ejabberd build is broken with lager 3.2.0 and the fix is already commited: https://github.com/basho/lager/commit/4c87abcd4f9d70a1136fff8f573dc7adcc833e43

It would be very helpful if you could release lager 3.2.1 to help streamline build chain for our project.

Thanks !

**Comment by macintux** [comment]
My apologies for the delay. I will get something out today.

**Comment by mremond** [comment]
@macintux No problem, I was just making sure you knew about the issue.
Many thanks for the feedback 👍

**Comment by macintux** [comment]
Released.
