### ISSUE TITLE
goldrush [JIRA: RIAK-2798]

### ISSUE THREAD

**Issue by tonyrog** [basho/lager#378]
Hi!
From what I can see goldrush is never used. The only calls to goldrush is to stop the application. What is it used for? 
Is it possible to remove this dependency?

**Comment by mrallen1** [comment]
It's used to [filter traces](https://github.com/basho/lager/blob/master/src/lager_util.erl#L417-L463).

**Comment by tonyrog** [comment]
Ok. Thanks. I missed that goldrush module names where not prefixed by goldrush_ ;-)
